name: tcrbert
channels:
  - huggingface
  - pytorch
  - nvidia
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - adjusttext=0.7.3
  - anndata=0.7.5
  - biopython=1.79
  - blast=2.5.0
  - cached_property=1.5.2
  - cudatoolkit=10.2
  - gdown=4.4.0
  - gitpython=3.1.9
  - hdf5=1.10.6
  - joblib=1.0.1
  - leidenalg=0.8.4
  - logomaker=0.8
  - louvain=0.7.0
  - matplotlib=3.4.2
  - matplotlib-base=3.4.2
  - matplotlib-venn=0.11.6
  - muscle=3.8.1551
  - neptune-client=0.10.4
  - numpy=1.20.1
  - pandas=1.2.3
  - pip=21.0.1
  - python=3.9.2
  - pytorch=1.8.0
  - python-levenshtein=0.12.2
  - scikit-bio=0.5.6
  - scikit-learn=0.24.1
  - scipy=1.6.0
  - seaborn=0.11.0
  - skorch=0.10.0
  - statsmodels=0.12.2
  - tensorboard=2.4.1
  - tokenizers=0.10.1
  - tqdm=4.50.2
  - transformers=4.4.2
  - ipywidgets
  - pip:
    - bertviz==1.1.0
    - h5py==3.2.1
    - scanpy==1.7.1
    - umap-learn==0.5.1
    - fair-esm==0.4.0
    - tape-proteins==0.3